### ISSUE TITLE
Lint issues

### ISSUE THREAD

**Issue by drgrigg** [zoeypeterson/w-e-b-du-bois_the-souls-of-black-folk#4]
Lint doesn't appear to like the titlecase of song titles which include such expressions as "A-Breaking".  But I'm not sure that lint is correct here. We'll need to check with Alex.

@acabal: SE titlecase wants to change "Wrestlin’ Jacob, the Day is A-Breaking" to "Wrestlin’ Jacob, the Day Is a-Breaking". Now, the change of lowercase "is" to capitalised "Is" is certainly correct, and should be changed. But "a-Breaking" just looks wrong, and so far as I can tell doesn't seem to match the Chicago Manual of Style titlecasing rules. "A-breaking" looks equally wrong. What do you think?

**Comment by acabal** [comment]
Yes, titlecase is wrong here. You can add an entry to se-lint-ignore.xml and I'll see if we can fix titlecase to work on this edge case.
