### ISSUE TITLE
Spelling issues

### ISSUE THREAD

**Issue by drgrigg** [zoeypeterson/w-e-b-du-bois_the-souls-of-black-folk#5]
Running se find-mismatched-dashes identifies issues: two instances of "cotton-fields" and two of "cottonfields". Modernize-spelling doesn't seem to want to take out the hyphen in "cotton-fields", and I think you should standardise on that version (with the hyphen).

Also, running se modernize-spelling picks up "Leipsic" in "of-the-wings-of-atlanta" which should be changed to "Leipzig". The other change it suggests, in "of-mr-booker-t-washington-and-others" wants to change what appears to be a surname and so should be ignored.

**Comment by zoeypeterson** [comment]
Done. Thanks for catching these.
